### ISSUE TITLE
Cannot resolve module "cssx" in module "infamous" although module "infamous" does not use "cssx".

### ISSUE THREAD

**Issue by trusktr** [krasimir/cssx#15]
I'm getting a really strange error. I have a package, `infamous`, and as you [can see](https://github.com/infamous/infamous/search?utf8=%E2%9C%93&q=cssx), it does not contain the word "cssx" anywhere in it's source code.

However, when I build my app with Webpack, I get the following extremely bizarre errors:

```
ERROR in ../infamous+infamous/motor-html/push-pane-layout.js
Module not found: Error: Cannot resolve module 'cssx' in /Users/trusktr/src/infamous+infamous/motor-html
 @ ../infamous+infamous/motor-html/push-pane-layout.js 31:12-29

ERROR in ../infamous+infamous/motor-html/push-pane-layout.js
Module not found: Error: Cannot resolve module 'cssx' in /Users/trusktr/src/infamous+infamous/motor-html
 @ ../infamous+infamous/motor-html/push-pane-layout.js 35:22-56
```

Not sure if this is related to CSSX, but since CSSX is mentioned in the error I thought I'd bring it up here. It could be some bizarre Webpack error. I don't seem to get this error when importing the same module using ES6 Modules in Meteor. Note also my `infamous` package is `npm link`ed, which has brought up issues in the past.

Any ideas?

**Comment by trusktr** [comment]
Aha! I remember now, indeed it is an error with no intuitive solution whatsoever: https://github.com/webpack/webpack/issues/811

(cc @sokra ^)

**Comment by krasimir** [comment]
Weird indeed.
