### ISSUE TITLE
Automatic default units subtitution

### ISSUE THREAD

**Issue by a-x-** [krasimir/cssx#22]
What if like react instead of
`line-height: {{ fontSize * 1.2 }}px;`
make possible write like this:
`line-height: {{ fontSize * 1.2 }};`

**Comment by krasimir** [comment]
Hi @a-x-,

CSSX is more like transpiler and do not analyze the code from a CSS point of view. I mean to achieve what you are suggesting we have to write logic that first understands the possible units for the property on the left. Like for example adding `px` to `background-url` doesn't make sense. So, we have to implement fairly custom logic which I prefer placing outside of CSSX. For example:
```
var sheet = cssx();
var fontSize = 20;
var unit = function (size) {
  if (/^\d+$/.test(size)) {
    return size + 'px';
  }
  return size;
}
var s = <style>
  .body {
    line-height: {{ unit(fontSize * 1.2) }};
    padding: {{ unit(fontSize + 'em') }};
  }
</style>;
sheet.add(s);
```
You may try this code here http://krasimir.github.io/cssx/playground/try-it-out/

**Comment by a-x-** [comment]
Thank you for detailed answer

i see, you're right
