### ISSUE TITLE
CSSX and rollup

### ISSUE THREAD

**Issue by vwochnik** [krasimir/cssx#23]
I am using `rollup` for my build process and I have tried using the CSSX transpiler within a `rollup` transformer. The issue, however, is that I don't know how to output a source map with the CSSX transpiler which is required by `rollup`.

Here is the bare minimum transformer I currently use:

```
import cssxTranspiler from 'cssx-transpiler';

function cssxTransform() {
  return {
    transform ( code, id ) {
      return { code: cssxTranspiler(code) /*, map: null */ };
    }
  };
}
```

Has anyone attempted to use CSSX with rollup or is there something already in the making?

**Comment by krasimir** [comment]
That's interesting. I never finished the source map generation. So if that's required by rollup it probably means that cssx can't work with it right now. I'll leave this open and will try making some free time to dig into source maps.

**Comment by vwochnik** [comment]
Maybe I can make a package out of this with a PR. So I have found the rollup plugin and here is the code tht will make CSSX work with `rollup`:

```
import cssxTranspiler from 'cssx-transpiler';
import MagicString from 'magic-string';
import { createFilter } from 'rollup-pluginutils';

export default function(options) {
  options = options || {};
  let filter = createFilter(options.include, options.exclude);

  return {
    transform(code, id) {
      if (!filter(id)) {
        return null;
      }

      let s = new MagicString(code);
      let out = cssxTranspiler(code, options);
      s.overwrite(0, code.length, out.toString())

      return  {
        code: s.toString(),
        map: s.generateMap({ hires: true })
      };
    }
  };
}
```

**Comment by krasimir** [comment]
> Maybe I can make a package out of this with a PR

That seems like a really nice idea. Let me know if it works and I'll add it to the README of CSSX.

**Comment by krasimir** [comment]
A PR (https://github.com/krasimir/cssx/pull/24) merged in.
