### ISSUE TITLE
How to create a scoped CSS for a component?

### ISSUE THREAD

**Issue by Danilo-Araujo-Silva** [krasimir/cssx#27]
First of all I would like to say this project is a very nice one!
I had a similar idea some time ago (bring the same power of jsx style to css) and I could say you are doing a very interesting job.

So I would like to ask, if we would like to create a style that is scoped on some of our react component how could we do that?

For example, in the [playground](http://krasimir.github.io/cssx/playground/try-it-out-bin/) we can see (inspecting the code) that the style created could affect all **p** tags. But what If we would like to affect just the **p** tags of some component?

The motivation for this is from Angular 4 (please see this [link](https://angular.io/guide/component-styles)). In Angular 4 we can style a component on a scoped way without affecting another ones. Can we achieve this with CSSX?

**Comment by krasimir** [comment]
Yep, it is possible by using [react-cssx](https://github.com/krasimir/react-cssx#scoping).

**Comment by Danilo-Araujo-Silva** [comment]
Very nice! Thanks a lot.
