### ISSUE TITLE
Usage with jspm

### ISSUE THREAD

**Issue by wesleycoder** [krasimir/cssx#5]
I'm loving this whole thing, but many people use jspm as base tool, would be possible to have cssx working together with jspm?

**Comment by krasimir** [comment]
Yep, of course. I'll post here once the integration is done.

**Comment by krasimir** [comment]
So, it wasn't so easy as I thought. There is a jspm example under the playground folder. Check it out [here](https://github.com/krasimir/cssx/tree/master/playground/jspm).
