### ISSUE TITLE
how do i get back in cssxDefinition context?

### ISSUE THREAD

**Issue by nrser** [krasimir/cssx#8]
just started evaluating the library, i'm trying to generate rules by mapping over an object (as i often do in React):

```
sheet.add(
  <style>
    .tile {
      {{ tileWidths.map(function(width, key) {
        return (
          @media (min-width: {{ widths[key] }}) {
            width: {{ width }};
          }
        );
      }) }}
    }
  </style>
);
```

transpiler is producing the following error:

```
[04:58:14] Plumber found unhandled error:
 SyntaxError: CSSX: Not in cssxDefinition context (37:8)
```

how do i indicate to the transpiler that i'm switching back to cssx?

i also tried this, to no avail:

```
sheet.add(
  <style>
    .tile {
      {{ tileWidths.map(function(width, key) {
        return (
          <style>
            @media (min-width: {{ widths[key] }}) {
              width: {{ width }};
            }
          </style>
        );
      }) }}
    }
  </style>
);
```

**Comment by krasimir** [comment]
CSSX allows similar expressions but even though they pass the CSSX-to-AST transformation they doesn't make sense for the AST-to-CSS bit. So, I think you should use:

```
var sheet = cssx();
var tileWidths = [1200, 500];

tileWidths.forEach(function(width) {
  sheet.add(<style>
  	@media (min-width: {{ width }}px) {
    	.title {
      	width: {{ width }}px;
    	}
  	}
  </style>);
});
```

That is transpiled to:
```js
var sheet = cssx();
var tileWidths = [1200, 500];

tileWidths.forEach(function (width) {
  sheet.add((function () {
    var _2 = {},
        _3 = {},
        _4 = {};
    _3['width'] = width + "px";
    _4['.title'] = _3;
    _2["@media (min-width: " + width + "px)"] = _4;
    return _2;
  }.apply(this)));
});
```
And results in the following CSS:
```css
@media (min-width: 1200px) {
  .title {
    width: 1200px;
  }
}
@media (min-width: 500px) {
  .title {
    width: 500px;
  }
}
```
*You can copy and paste the code [here](http://krasimir.github.io/cssx/playground/try-it-out/).*

**Comment by krasimir** [comment]
Have in mind that you can combine rules and pass them at different time to the same media query definition. For example:

```
var sheet = cssx();
var media = sheet.add(<style>@media (min-width: 1200px) {}</style>);

media.nested(<style>.title { font-size: 20px; }</style>);
media.nested(<style>.small { line-height: 12px; }</style>);
```

**Comment by krasimir** [comment]
@nrser did you manage to solve your problem?

**Comment by nrser** [comment]
sorry, i'd been traveling and busy with other stuff.

yeah, thanks, i wasn't really thinking about it correctly... i was rushing through evaluating a few different CSS solutions and trying to port code over from less.

as i recall, the nesting in less is part of the less language and doesn't exist in standard css, so i shouldn't have expected it to directly translate.
